### ISSUE TITLE
Cant create more then 999 tiles from one texture

### ISSUE THREAD

**Issue by kondelik** [puppetmaster-/tileset_plugin#26]
I have 1024x1024 texture with 32x32 tiles (= (1024/32)^2 = 1024 tiles).

Cant generate tiles, becouse "To" textbox is only 3 chars long...

![only_3_chars_to](https://user-images.githubusercontent.com/4945875/33377831-25c75532-d513-11e7-9f41-95d87338e79f.png)

**Comment by puppetmaster-** [comment]
The newest version is now on the AssetLib and you can now create more then 999 tiles.

**Comment by kondelik** [comment]
Confirm, it's working, thanks.
