### ISSUE TITLE
shift created nodes

### ISSUE THREAD

**Issue by adfaure** [puppetmaster-/tileset_plugin#27]
When the nodes are generated, it could be nice to dispose them next to each other.

**Comment by puppetmaster-** [comment]
@adfaure In the last release (https://godotengine.org/asset-library/asset/edit/374) there are now next to each other. You can donwload the relase on github or wait or wait until it's confirmed.

**Comment by adfaure** [comment]
I admit I did not dig that much, It was a suggestion. 
Since it will be released I close the issue.
Thank you for the information ;)

**Comment by puppetmaster-** [comment]
@adfaure np :)
