### ISSUE TITLE
it won't work with tilesets of 1 column

### ISSUE THREAD

**Issue by LeonardoCunhaGitHub** [puppetmaster-/tileset_plugin#28]
thank you for providing this awesome tool!

I got this Tileset with 4 tiles of 16x16px each and placed vertically in one column:
![tileset](https://user-images.githubusercontent.com/22682585/34461906-f72f5b14-ee1e-11e7-9a04-a29195704a36.png)

When I type 16 on the field SIZE the FRAME field remains disabled.
![image](https://user-images.githubusercontent.com/22682585/34461911-22b6ad5a-ee1f-11e7-826a-88dd9b852baa.png)

If I create the same Tileset with 1 row then it works:
![tileset](https://user-images.githubusercontent.com/22682585/34461944-c1d59c02-ee1f-11e7-9c31-2f09162c701c.png)

![image](https://user-images.githubusercontent.com/22682585/34461936-ac4aac9c-ee1f-11e7-8de9-7c7db2879703.png)

**Comment by puppetmaster-** [comment]
@LeonardoCunhaGitHub Thanks for reporting the bug. It is fixed now. Please let me know if it works.

**Comment by LeonardoCunhaGitHub** [comment]
@puppetmaster- Thank you so much. Awesome
