### ISSUE TITLE
Compatibility with Godot 3.0

### ISSUE THREAD

**Issue by Trixu** [puppetmaster-/tileset_plugin#29]
Hi and thank you for this tool,
Are you going to make it work with Godot 3.0?

**Comment by puppetmaster-** [comment]
I've been working on the implementation since last night.
But I still have to finish the new tile properties implementation.

**Comment by puppetmaster-** [comment]
![tileset_plugin](https://user-images.githubusercontent.com/10463138/35593624-a3dfff54-0610-11e8-81b6-3eda4a7dc436.png)
Its done. Need to update the Asset Store!

**Comment by puppetmaster-** [comment]
plugin are now in AssetLib available
