### ISSUE TITLE
I can't get it working with more than one tile image

### ISSUE THREAD

**Issue by danielytics** [puppetmaster-/tileset_plugin#30]
The thumbnail shows up as the multiple-file image, but it only inserts one tile. Selecting existing tiles and using the plugin to modify them does work, however.

**Comment by puppetmaster-** [comment]
~~Are u using the godot 2 or godot 3 plugin?~~
@danielytics Found the problem! It has something to do with the name.
QuickFix (inside function addImageNodes )
![image](https://user-images.githubusercontent.com/10463138/37557194-5051c2a4-2a01-11e8-84b5-0efe930e9e70.png)
Thank you for reporting!

**Comment by danielytics** [comment]
Thanks for the fix!
