### ISSUE TITLE
add 1d index numbering system

### ISSUE THREAD

**Issue by Shadowblitz16** [puppetmaster-/tileset_plugin#31]
please add 1d numbering system starting from 0 naming like so
tile_0..
tile_1..
tile_2..

and please when using 2d numbering system use name them like so..
tile_0_0..
tile_1_0..
tile_2_0..

**Comment by puppetmaster-** [comment]
Have you tried these settings yet?
**Godot 2**
![image](https://user-images.githubusercontent.com/10463138/54722532-0e95f700-4b65-11e9-914f-289d48360f1d.png)

**Godot 3**
![image](https://user-images.githubusercontent.com/10463138/54723082-af38e680-4b66-11e9-8e5d-e4977019d8e2.png)

I don't use my own logic for the node names instead I use the automatic one from Godot.

**Comment by Shadowblitz16** [comment]
oh ok I will try it next time
