### ISSUE TITLE
Update to support Godot 4

### ISSUE THREAD

**Issue by JeremyMCastillo** [puppetmaster-/tileset_plugin#32]
Are there any plans currently to update this plugin to support Godot 4? I am interested in using this plugin for a current project, and I have started porting it myself. If it's ok I can submit a Pull Request of the ported version to this repo.

**Comment by puppetmaster-** [comment]
I thought that with Godot 4 and its improved Tilemap editor, there would be no interest in my plugin anymore. If the plugin is useful to you, feel free to submit a Pull Request, and I'll be happy to merge it.

**Comment by JeremyMCastillo** [comment]
Understood, I'm new to Godot and was not yet familiar with the v4 Tilemap tools. It seems this tool should live on in v3 projects!
