### ISSUE TITLE
Packaging your plugin for the assetlib

### ISSUE THREAD

**Issue by akien-mga** [puppetmaster-/tileset_plugin#5]
You can submit it via https://godotengine.org/asset-library (alpha frontend, expect some bugs/UX issues).

When you submit a download link, remember that the sha256sum of the zip archive is used to validate the asset (so that moderators don't validate an asset that would later be turned into something bad, each new version has to be moderated). So to prevent the download from being invalidated at your next commit, don't use the zip archive of the master branch, but instead of the latest commit: https://github.com/puppetmaster-/tileset_plugin/archive/fb5b8e09dcb3d8e4b0123b34b030164172fa4e5d.zip
(or tag a version).

**Comment by puppetmaster-** [comment]
thank you for the information

**Comment by puppetmaster-** [comment]
asset created, waiting for confirmation

**Comment by akien-mga** [comment]
Thanks, accepted: https://godotengine.org/asset-library/asset/9

**Comment by akien-mga** [comment]
Looks like the previews were not kept, that's a bug of the frontend.

**Comment by akien-mga** [comment]
Reported as https://github.com/godotengine/asset-library/issues/44

**Comment by puppetmaster-** [comment]
When waiting for confirmation it  doesn't show up under my asset. Feels like something went wrong.
