### ISSUE TITLE
Mipmap/filter/tilles-less loading

### ISSUE THREAD

**Issue by morphles** [puppetmaster-/tileset_plugin#6]
Currently ImageTexture is created with default flags, meaning mimaps and tiling is enabled. Leading to imported being blury and having wrap-around artifacts, esp when scaled. I would think that that is mostly undesired, and there should be at least an option to disabled them. I'm quite new to godot and gdscript, and a bit lazy to contribute full patch with ui changes, still I made local modification to load without mipmaps and wrapping (names are also not great for vars, still hopefully that is useful):

```
diff --git a/addons/tileset_dock/tileset_dock_plugin.gd b/addons/tileset_dock/tileset_dock_plugin.gd
index ee890d2..15803f0 100644
--- a/addons/tileset_dock/tileset_dock_plugin.gd
+++ b/addons/tileset_dock/tileset_dock_plugin.gd
@@ -230,8 +230,10 @@ func addImageNodes():
        print("creating ",imagesPath.size()," sprites from selection")
        var _root =  get_tree().get_edited_scene_root()
        for _path in imagesPath:
+               var _img = Image()
+               _img.load(_path)
                var _image  = ImageTexture.new()
-               _image.load(_path)
+               _image.create_from_image(_img, 0)
                tileSize = _image.get_width()
                var _imageName = getFileName(_path)
                var _spriteNode
```

**Comment by puppetmaster-** [comment]
thank you for informing me about the problem with the image flag and vars name
